
### Bus Arrival
GET {{baseURL}}/ltaodataservice/BusArrivalv2?BusStopCode=77049
AccountKey: {{authorization}}

### Bus Arrival with Bus Service No
GET {{baseURL}}/ltaodataservice/BusArrivalv2?BusStopCode=01019&ServiceNo=12
AccountKey: {{authorization}}

### Bus Routes
GET {{baseURL}}/ltaodataservice/BusRoutes?$skip=0
AccountKey: {{authorization}}

### Bus Stops
GET {{baseURL}}/ltaodataservice/BusStops?$skip=0
AccountKey: {{authorization}}

### Bus Services
GET {{baseURL}}/ltaodataservice/BusServices
AccountKey: {{authorization}}