name: lta_datamall_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 18.0.0+2000000003

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  convex_bottom_bar: ^3.2.0
  dio: ^5.8.0+1
  drift: ^2.25.1
  firebase_analytics: ^11.4.2
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  firebase_performance: ^0.10.1
  firebase_remote_config: ^5.4.0
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_staggered_animations: ^1.1.1
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
  go_router: ^14.8.0
  in_app_review: ^2.0.10
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  sqlite3_flutter_libs: ^0.5.30
  substring_highlight: ^1.0.33
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  drift_dev: ^2.25.2
  firebase_core_platform_interface: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter_icons:
  android: true
  ios: true
  image_path: "images/app-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/city.flr
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
