name: lta_datamall_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.1+112

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  convex_bottom_bar: ^3.0.0
  dio: ^4.0.0
  firebase_analytics: ^8.1.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  firebase_performance: ^0.7.0+3
  flare_flutter: ^3.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  flutter_staggered_animations: ^1.0.0
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^0.14.0+3
  injectable: ^1.4.0
  json_annotation: ^4.0.1
  latlong2: ^0.8.0
  location: ^4.1.1
  logging: ^1.0.1
  path: ^1.8.0
  pedantic: ^1.11.0
  rate_my_app: ^1.1.0+1
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.4
  # substring_highlight: ^0.1.2
  # screenshots: ^2.1.1
  #navigation
  #stack service

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.0
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.2
  mockito: ^5.0.8

# dependency_overrides:
#   screenshots:
#     git: https://github.com/trygvis/screenshots
#   tool_base:
#     git: https://github.com/speaking-in-code/tool_base
#   tool_base_test:
#     git: https://github.com/trygvis/tool_base_test
#   tool_mobile:
#     git: https://github.com/trygvis/tool_mobile
#   fake_process_manager:
#     git: https://github.com/trygvis/fake_process_manager
# dependency_overrides:
#   process: ^4.0.0-nullsafety.1
#   platform: ^3.0.0-nullsafety.1
#   file: ^6.0.0-nullsafety.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/app-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/city.flr
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
