name: lta_datamall_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+500

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  convex_bottom_bar: ^3.2.0
  dio: ^5.3.2
  drift: ^2.11.0
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_performance: ^0.9.2+5
  firebase_remote_config: ^4.2.5
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  flutter_staggered_animations: ^1.1.1
  freezed_annotation: ^2.4.1
  geolocator: ^10.0.0
  go_router: ^10.1.0
  in_app_review: ^2.0.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.1
  path: ^1.8.3
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.2
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  sqlite3_flutter_libs: ^0.5.15
  substring_highlight: ^1.0.33
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  drift_dev: ^2.11.0
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/app-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/city.flr
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
