// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNTIhjD-7OpMed8eoa5s-2gLSby4cYWjc',
    appId: '1:993014486723:android:02a1190c04bc1237827476',
    messagingSenderId: '993014486723',
    projectId: 'lta-datamall',
    databaseURL: 'https://lta-datamall.firebaseio.com',
    storageBucket: 'lta-datamall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9rNg6mm3vJI7Ej5NI9GS9MzYei-KJDk',
    appId: '1:993014486723:ios:3e667c9450c311aa827476',
    messagingSenderId: '993014486723',
    projectId: 'lta-datamall',
    databaseURL: 'https://lta-datamall.firebaseio.com',
    storageBucket: 'lta-datamall.appspot.com',
    iosClientId: '993014486723-3ct22c01msn2arnv056holhc0e4cbda0.apps.googleusercontent.com',
    iosBundleId: 'com.saschaderungs.ltaDatamall',
  );
}
