# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Push a new beta build to TestFlight"
  lane :test do
    Dir.chdir "../.." do
      sh("flutter", "analyze")
      sh("flutter", "test")
    end
  end

  lane :increment_build_number_ios do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
  end

  lane :testflight_from_local do
    match(type: "appstore", readonly: is_ci)
    build_ios_app(
      export_method: "app-store"
    )
    upload_to_testflight
  end

  desc "Registers new devices to Dev Portal and auto re-generate the provisioning profile if necessary"
  lane :add_new_devices do
    register_devices(
      devices: {
        "Device name" => "UDID-XXXXXX"
      }
    )
    match(type: "adhoc", force_for_new_devices: true)
  end

  desc "Upload to Firebase"
  lane :upload_firebase do
    match(
      type: "adhoc",
      readonly: true,
      app_identifier: "com.saschaderungs.ltaDatamall"
    )
    update_code_signing_settings(
      code_sign_identity: "iPhone Distribution",
      use_automatic_signing: false
    )
    build_ios_app(
      export_method: "ad-hoc",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          "com.saschaderungs.ltaDatamall" => "match AdHoc com.saschaderungs.ltaDatamall"
        }
      },
      xcargs: {
        "PROVISIONING_PROFILE_SPECIFIER" => "match AdHoc com.saschaderungs.ltaDatamall",
      }
    )
    firebase_app_distribution(
      app: "1:993014486723:ios:3e667c9450c311aa827476",
      release_notes: "This is a distribution build!",
      groups: "sglandtransport_internal_test_group",
      debug: true
    )
  end

  lane :testflight_from_ci do
    match(
      type: "appstore",
      readonly: is_ci,
      app_identifier: "com.saschaderungs.ltaDatamall"
    )
    update_code_signing_settings(
      code_sign_identity: "iPhone Distribution",
      use_automatic_signing: false
    )
    build_ios_app(
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.saschaderungs.ltaDatamall" => "match AppStore com.saschaderungs.ltaDatamall"
        }
      },
      xcargs: {
        "PROVISIONING_PROFILE_SPECIFIER" => "match AppStore com.saschaderungs.ltaDatamall",
      }
    )
    upload_to_testflight
    upload_to_app_store(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: true,
      overwrite_screenshots: true
    )
  end

  lane :submit_review do
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true
      }
    )
  end

  lane :test_match do
    match(
      type: "appstore",
      readonly: is_ci,
    )

  end
end
