# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :test do
    Dir.chdir "../.." do
      sh("flutter", "analyze")
      sh("flutter", "test")
    end
  end

  lane :beta do
    ensure_git_status_clean
    git_pull
    ensure_git_status_clean
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    Dir.chdir "../.." do
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      clean: true
    )
    upload_to_testflight
    commit_version_bump
    push_to_git_remote
  end

  lane :meta_data do
    upload_to_app_store(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: true,
      overwrite_screenshots: true
    )
  end

  lane :submit_review do
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true
      }
    )
  end
end
