# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    Dir.chdir "../.." do
      sh("flutter", "analyze")
      sh("flutter", "test")
      sh("flutter", "build", "appbundle")
    end
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_internal do
    Dir.chdir "../.." do
      sh("flutter", "analyze")
      sh("flutter", "test")
      sh("flutter", "build", "appbundle")
    end
    upload_to_play_store(track: "internal", aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
end
