name: Test Release Creation
on: 
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release Name'     
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Release Name: ${{ github.event.inputs.releaseName }}"
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "${{ github.event.inputs.releaseName }}+${{ github.run_number }}"
        tag: "${{ github.event.inputs.releaseName }}+${{ github.run_number }}"
        allowUpdates: false