name: PR on master
on:
  push:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.0'
    - name: Analyze code
      run: flutter analyze
  playstore:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.0'
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Configure Keystore
      run: |
        cd android
        echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
        echo "storeFile=keystore.jks" > key.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
      env:
        ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
    - name: Create Google Play Config file
      run : |
        cd android
        echo "$PLAY_CONFIG_JSON" > play_config.json.b64
        base64 -d -i play_config.json.b64 > play_config.json
      env:
        PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
    - name: Add Google Services file
      run : |
        cd android
        echo "$ANDROID_GOOGLE_SERVICES" > google-services.json.b64
        base64 -d -i google-services.json.b64 > app/google-services.json
      env:
        ANDROID_GOOGLE_SERVICES: ${{ secrets.ANDROID_GOOGLE_SERVICES }}
    - name: Build appbundle
      run: |
        flutter pub get
        flutter build appbundle --dart-define=LTA_DATAMALL_API_KEY=${{ secrets.LTA_DATAMALL_API_KEY }}
    - name: Upload to Play Store Test Lane
      run: |
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        cd android
        bundle install
        bundle exec fastlane deploy_internal
  testflight:
    runs-on: macos-latest
    needs: analyze
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.0'
    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Add Google Services file
      run: echo "${{ secrets.IOS_GOOGLE_SERVICES }}" > ios/GoogleService-Info.plist
    - name: Build IPA
      run: |
        flutter pub get
        flutter build ios --release --no-codesign --dart-define=LTA_DATAMALL_API_KEY=${{ secrets.LTA_DATAMALL_API_KEY }}
    - name: Upload to TestFlight
      run: |
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
        cd ios
        bundle install
        bundle exec fastlane testflight_from_ci
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}