name: Release
on: 
  workflow_dispatch

jobs:
  google:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: android
      - name: Promote
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd android
          bundle exec fastlane promote_production