name: Test
on:
  push:
    branches: [master]
    paths:
      - "lib/**"
      - "test/**"
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "12.x"
          distribution: 'zulu'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Prepare
        run: |
          flutter pub get
          flutter pub run build_runner build
      - name: Analyze
        run: flutter analyze
      - name: Ensure complete test covered
        run: sh scripts/import_files_coverage.sh lta_datamall_flutter
      - name: Unit Test
        run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          files: ./coverage/lcov.info
